name: Build Debug APK

on:
  workflow_dispatch:  # Only manual triggering

permissions:
  contents: write  # Required to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Fix gradle.properties
        run: |
          if [ -f "android/gradle.properties" ]; then
            sed -i '/org.gradle.java.home/d' android/gradle.properties
            echo "# Removed Windows JDK path for CI build" >> android/gradle.properties
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get
        
      - name: Accept Android SDK Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.13113456"

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: debug-build-${{ github.run_number }}
          name: Debug Build ${{ github.run_number }}
          body: "Automated debug build from GitHub Actions"
          draft: false
          prerelease: true
          files: build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 